#!/usr/bin/env python3
"""개발용 외부 MoAI-ADK 진입 스킬을 commands.json에서 재생성한다."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / ".agents/skills"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    records = json.loads((BASE / "commands.json").read_text(encoding="utf-8"))
    errors = []
    for entry in records:
        body = f'''---
# Generated by scripts/sync-dev-skills.py; edit commands.json and regenerate.
name: {entry["name"]}
description: {json.dumps(entry["description"], ensure_ascii=False)}
---

이 스킬은 별도 MoAI-ADK의 개발 워크플로우 진입점이다. MoAI-Cowork 실무 플러그인에 포함되는 스킬이 아니다.

1. 현재 세션에 `moai` 스킬이 실제 노출되면 해당 정본을 읽고 다음 인수를 전달한다: `{entry["arguments"]}`.
2. `moai` 스킬이 없으면 `moai --help`로 설치·명령 표면만 확인한다. 이름이 비슷한 Cowork 스킬을 대신 실행하지 않는다.
3. 실제 제공되는 CLI 동작과 필요한 입력·권한·검증 절차를 확인할 수 있는 범위에서만 진행한다. 확인할 수 없으면 외부 MoAI-ADK 의존성이 없다는 blocker와 필요한 설치 또는 진입 경로를 보고한다.
4. 스킬을 읽지 못했거나 업무를 실행하지 않은 상태를 완료로 보고하지 않는다.
'''
        path = BASE / entry["name"] / "SKILL.md"
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != body:
                errors.append(entry["name"])
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body, encoding="utf-8")
    print(json.dumps({"wrappers": len(records), "errors": errors}, ensure_ascii=False))
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
